### ISSUE TITLE
🐛 BUG: Difference in redirects parsing for Pages Direct Upload

### ISSUE THREAD

**Issue by KianNH** [cloudflare/wrangler2#1242]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Windows

### Describe the Bug

There appears to be a difference in the `_headers` and `_redirects` parsing when using `wrangler pages publish` or the dashboard direct upload for Cloudflare Pages.

* The following redirect rule (`/:_/* /`) works through the Git integration but not direct upload.

```sh
# Git integration
curl https://pages-du-test.pages.dev/foo/bar -sSI
HTTP/1.1 302 Found
```

```sh
# Direct Upload
curl https://foo-86b.pages.dev/foo/bar -sSI
HTTP/1.1 200 OK
```

* The dashboard does not show the parsed redirects/headers, despite them working.

![image](https://user-images.githubusercontent.com/94662631/173311157-9be0de27-ef00-4733-a367-7c6dfc505e05.png)

![image](https://user-images.githubusercontent.com/94662631/173311170-011402fd-9db1-43fb-820d-a4f112570313.png)

**Comment by KianNH** [comment]
[Related community post](https://community.cloudflare.com/t/bug-direct-uploads-failed-to-parse-redirects-and-headers-files/390733?u=kiannh)

**Comment by booleanbetrayal** [comment]
This is blocking our adoption of Direct Push. Is this actively being worked on?

**Comment by hectcastro** [comment]
I believe that I am hitting this issue as well. The following redirect rule is the only rule in my `_redirects` file:

```
/*.html /:splat/ 301
```

When deploying using `wrangler pages publish`, the rule does not appear to take effect. However, when I use the Cloudflare Pages builders to deploy the same Git revision, the rule functions.

The details above about the inconsistencies in the UI appear to remain also. Details about the redirect rule display when processed by the builders, but not Direct Upload.

**Comment by keenwon** [comment]
I had the same problem.

```
/*.html /:splat/ 301
```

not work with `wrangler pages publish`

**Comment by keenwon** [comment]
Any update on this issue?

**Comment by booleanbetrayal** [comment]
Cloudflare should stop [promoting use cases that are actually broken](https://blog.cloudflare.com/cloudflare-pages-direct-uploads/) under the hood. Can we please get a fix ETA for this?

**Comment by heath-pack** [comment]
Bumping this. Is there actually any plan on fixing this issue?

**Comment by justinschier** [comment]
Bumpity bump. Could really use a fix for this.

**Comment by jahands** [comment]
Thank you for the report and everyone's patience - this is now fixed

**Comment by keenwon** [comment]
@jahands The _headers and _redirects are still not visible in the dashboard

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/5516478/185553849-0a7c54b6-24cf-4e91-abd4-4a5fdb3c53cd.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5516478/185553899-07d3205e-bc9b-4e3c-ba6e-4c141b8365d9.png">

**Comment by jahands** [comment]
Thanks @keenwon - that is a separate issue to this issue however (which we have an internal ticket for.)
These files are getting applied, they just aren't showing up in the Dash UI
