### ISSUE TITLE
🐛 BUG: wrangler2 can not decode `[` and `]`

### ISSUE THREAD

**Issue by dgokcin** [cloudflare/wrangler2#1437]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

Mac

## Description
When I serve my next app statically with `wrangler pages dev out`, I believe wrangler is failing to decode `[id]` and throwing me a 404 error. When I examine the network tab of the developer console, I see that the failing request is to `%5Bid%5D`. However the same request results with a 200 response on Cloudflare Pages. Also if I edit the failing GET request by replacing the `%5B` and `%5D` with `[` and `]`, I get a 200 response. I believe there is something wrong with the decoding of `[` and `]`.
![image](https://user-images.githubusercontent.com/33603535/178061295-74cd8a1f-9cc9-4770-8dc1-a20aa12728c9.png)

## Steps to Reproduce
- Create a next app with `yarn create next app pages-example`
- Add ` "export": "next export"` to package.json
- create a directory under `/pages` named p and create an empty `[id].js` file.
- fill the file with the following content
  ```js
  import React  from 'react';
  import { useRouter } from 'next/router';
  
  const Page = () => {
	  const router = useRouter();
  
	  const { id } = router.query;
  
	  console.log(id, router);
	  return (
		  <div>
			  id from url: { id } 
		  </div>
	  );
  };
  
  export default Page;
  ```
- create a `/functions/p/[id].js` with the following content
  ```js
  export function onRequestGet({ env, request, params }) {
    console.log("entering the function")
    console.log("env", env)
    console.log("request", request)
    return env.ASSETS.fetch(new Request(new URL('/p/[id]', request.url).toString(), request));
  }
  
  ```
- run `yarn build && yarn export`
- run `wrangler pages dev out`
- type `http://localhost:8788/p/12` to the address bar.

**Comment by Hexstream** [comment]
I don't understand why you would use brackets as a part of any URL in this context.

Your id matched by the `[id]` part of the corresponding Pages Functions filename would then be literally `[id]`, which seems nonsensical.

**Comment by dgokcin** [comment]
> I don't understand why you would use brackets as a part of any URL in this context.
> 
> Your id matched by the `[id]` part of the corresponding Pages Functions filename would then be literally `[id]`, which seems nonsensical.

I am not using brackets as the part of the url. I believe it is happening in the background when wrangler is running in pages dev mode.

I am using nextjs [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes) in my project which is deployed to cloudflare pages. I add dynamic routing capability to my pages app by writing a function under, '/functions/orders/[id].js' since it is not supported by default. 

So when there is a get request sent to 'orders/someId' my function is triggered, fetches the correct asset. In the network tab, I see that in my local machine, a specific js chunk associated with the html file, throws a 404 error, where on my pages app, the same request returns a 200 response.
it looks like wranglers static assets fail to decode, `[id]` to `%5Bid%5D`

so brackets in the url is not something I am doing on purpose, it is because I have dynamic routes in my project.

**Comment by sidharthachatterjee** [comment]
I'm unsure but I have a feeling that https://github.com/cloudflare/wrangler2/pull/1431 might resolve this. @GregBrimble Can you confirm? 

Thanks for the bug report in the mean time. This is certainly a bug indeed.

**Comment by dgokcin** [comment]
@sidharthachatterjee any updates?

**Comment by Skye-31** [comment]
It's possible #1552 fixed this?

**Comment by dgokcin** [comment]
@Skye-31 I can test it tomorrow and let you know!

**Comment by dgokcin** [comment]
@Skye-31 #1552 has not fixed this issue. It still happens with wrangler 2.0.23

![image](https://user-images.githubusercontent.com/33603535/182081899-8e303d1f-e02c-4d15-83ea-796e892f88e2.png)

**Comment by threepointone** [comment]
It's not out in a release yet, should go out today. Could you try with wrangler@beta?

**Comment by dgokcin** [comment]
just tried it with beta, same result.

![image](https://user-images.githubusercontent.com/33603535/182118217-0884204c-66a5-4095-89a4-46e79b30a148.png)

**Comment by Skye-31** [comment]
Could you try #1589 @dgokcin

**Comment by dgokcin** [comment]
#1589 works!!!

**Comment by dgokcin** [comment]
any information about when this could be merged?

**Comment by Skye-31** [comment]
It will need to be approved, then whenever we next do a release, it'll be good to go. You should be fine to stay on that branch until then though 🙂

**Comment by dgokcin** [comment]
great thanks!!!

**Comment by dgokcin** [comment]
@Hexstream my issue is fixed with the pr referenced above.

**Comment by Hexstream** [comment]
That's great to hear!

Unfortunately this doesn't seem to fix #1338, so I believe that issue should be reopened, since this appears to be a different issue after all.

**Comment by Skye-31** [comment]
I'll have a look into resolving that in the morning 🙂
