### ISSUE TITLE
wrangler can silently override environment variables that were set elsewhere

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#276]
To reproduce:

1. `wrangler init` to create a `wrangler.toml` with only a compatibility date.
2. `wrangler publish --name new-worker` to deploy the worker script.
2. Go to `dash.cloudflare.com` > Workers > new-worker > settings > variables > Add Variable. Do not encrypt the variable.
3. Re-publish the worker script. The environment variable will disappear.

Note this does not affect secrets, although `wrangler secret put` will overwrite existing secrets in the dashboard.

**Comment by Electroid** [comment]
What should the new behaviour be? Here are a few options:
* wrangler checks for previous environment variables and errors on publish if a variable was removed; asks for confirmation.
   * Should there be a `--force` toggle that you can use in CI?
* wrangler no longer stores environment variables in its config, they are treated like secrets.
   * In the future, we would want to handle `.env` files though?

**Comment by Warfields** [comment]
Found the API for retrieving bindings, we can query at runtime and compare values.

<img width="1024" alt="Screen Shot 2022-01-25 at 9 52 00 PM" src="https://user-images.githubusercontent.com/32973228/151106162-cbfbe254-f60f-42c1-8c61-47b61db1b6f1.png">

**Comment by jspspike** [comment]
There is now a metadata parameter on script upload called `keep_bindings` which takes an array of binding types to retain from the previous upload. Environment variables have the type `plain_text` so having the upload metadata look like
```json
"main_module": "...",
"bindings": [...],
"keep_bindings": ["plain_text"],
```
will retain previous environment variables.

**Comment by threepointone** [comment]
We merged a change into wrangler that will, on publish, NOT delete any vars that were previously defined, and aren't included in wrangler.toml any more. This should remove some confusion about vars that disappear on publish. 

This also means devs are free to define vars with the dashboard, and edit them at any time, and they won't be blown away or updated when `wrangler publish` is called. Note to clarify: To be excluded from updating when the worker is published, these vars must NOT be defined in wrangler.toml. This behaviour seems more intuitive and should unblock most people. 

The release including these changes should go out early next week (usually monday morning), but they can try `wrangler@beta` if anyone would like to try these changes out sooner. 

---

Additionally, we've landed a feature for defining vars as CLI args. You can now do `wrangler publish --var name1:value1 --var name2:value2 --var name3:$SOME_ENV_VAR` to define vars. These vars behave like setting them in the dashboard; they won't be updated on wrangler publish if they're not included in wrangler.toml. See this pull request for more details https://github.com/cloudflare/wrangler2/pull/1730 (until we document this further in the main docs). This may also be useful to people.

Closing this issue.

**Comment by dusterio** [comment]
It's still happening for us, even with the latest version of wrangler (3.1.1). Wrangler deletes all environment variables on deploy, regardless of whether they are included in the wrangler config or not

**Comment by dusterio** [comment]
For anybody coming here from search, it's a CLI parameter now:
```/bin/bash
wrangler --keep-vars
```

**Comment by lukamo1996** [comment]
> --keep-vars

You're a saviour🙌

**Comment by Sultanbek9899** [comment]
Hello, does anyone know how to upload environment variables to worker settings env vars? Using API and Python?

**Comment by willie** [comment]
I want to be able to set env vars from my shell and use some of their values as the value for some things I define now in .dev.vars.

**Comment by juanmiguelguerrero** [comment]
My experience with this is very bad.

Variables that are created in the Dashboard should not be deleted when deploying the worker.

This does not work as expected.

**Comment by magick93** [comment]
I'm using `npx wrangler deploy --keep-vars --minify src/index.ts` and it is still overwriting environment variables set via the dashboard.

**Comment by rohanrichards** [comment]
This still is an issue in 2025, every time I push to main and it re-deploys I lose a bunch of env vars, I even added them back to my .toml file and they're being deleted. My Worker just feels completely broken currently as I lose all of my vars on every deploy.

**Comment by oldbettie** [comment]
yep same problem. Crazy that this has existed for 3 years

**Comment by leetindell** [comment]
For what its worth, I've found so far (new to Cloudflare workers) that if you set:

`"keep_vars": true,`

In the wrangler file (I'm using .json) within your project, any subsequent deploy/build does not overwrite the env vars you previously added directly within the Cloudflare dashboard.

They briefly mention it in the docs here: https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth

> If you change your environment variables in the Cloudflare dashboard, Wrangler will override them the next time you deploy. If you want to disable this behavior, add keep_vars = true to your Wrangler configuration file.

I can't speak to what happens if you have vars defined in the wrangler file though. I assume the same applies, whatever is added in the dashboard previously takes precedent and is unchanged.

**Comment by nextheme** [comment]
There is a cli tool that I use which is open source
[EnvCF](https://github.com/novincode/envcf)
`npx envcf --help`

It's built on top up of wrangler and it helps you scan and push all the envs.
