### ISSUE TITLE
🐛 BUG: SvelteKit Still Had Null Body Response Error

### ISSUE THREAD

**Issue by DevOfManyThings** [cloudflare/wrangler2#394]
### What version of `Wrangler` are you using?

0.0.15

### What operating system are you using?

Windows

### Describe the Bug

SvelteKit still gets null body response error which was fixed in https://github.com/cloudflare/miniflare/releases/tag/v2.0.0-rc.3, not sure how Wrangler2 incorporates miniflare, is there a pending version update or is this a separate issue?

**SETUP**
```
npm init svelte@next my-app
npm i --save-dev @sveltejs/adapter-cloudflare@next
Update svelte.config.js to use adapter.
npm install
```

**LAUNCH**
`npx wrangler pages dev --proxy 3000 -- npx svelte-kit dev --host
`
**ERROR**
When viewing project on _http://localhost:8788/_ page will alternate between rendering correctly and showing this:
![image](https://user-images.githubusercontent.com/6001393/152646473-0888246c-f476-445b-a5d7-4d6bbb2366fb.png)

**BEHAVIOR**
When viewing same page with network tab open and _disable cache_ enabled, error does not occur

Output:
```
[pages:err] GET /: TypeError: Response with null body status cannot have body
    at new Response (E:\Programming\Projects\ArtPageSvelteWrangler\node_modules\undici\lib\fetch\response.js:160:15)
    at new Response (E:\Programming\Projects\ArtPageSvelteWrangler\node_modules\@miniflare\core\src\standards\http.ts:556:13)
    at Object.construct (E:\Programming\Projects\ArtPageSvelteWrangler\node_modules\@miniflare\core\src\plugins\core.ts:69:29)
    at Object.fetch (<script>:5:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EventTarget.[kDispatchFetch] (E:\Programming\Projects\ArtPageSvelteWrangler\node_modules\@miniflare\core\src\standards\event.ts:359:13)
    at Server.<anonymous> (E:\Programming\Projects\ArtPageSvelteWrangler\node_modules\@miniflare\http-server\src\index.ts:167:20)
GET / 500 Internal Server Error (22.61ms)
```

**Comment by threepointone** [comment]
Thank you for reporting this, and sorry for the trouble! Could you try this with `wrangler@alpha`? There's a small chance we've already fixed this, but I'm not sure atm.

**Comment by DevOfManyThings** [comment]
No trouble at all! All comes with the fun of using new things eh?

Wrangler was updated to `0.0.0-536c7e5` and issue still occurs with same behaviour as above.

**Comment by threepointone** [comment]
Well damn. Alright, we'll figure this out. Thanks again for the report!

**Comment by GregBrimble** [comment]
Don't know where it is, but this is because somewhere (either in wrangler or in SvelteKit), a Response is being constructed incorrectly.

I've made the mistake myself several times before (usually when cloning an existing Response). [This](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/pages/functions/template-worker.ts#L110-L114) is what you need to do.

**Comment by GregBrimble** [comment]
Completely untested, but looks like it might be this line in SvelteKit: https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare/files/worker.js#L17

**Comment by petebacondarwin** [comment]
Had a quick look at this. It seems that the Worker is returning a `304 - Unmodified` response that also has a body, which undici is then complaining about. It might have been that this was also the case (?) but we were using a http client that didn't complain about this?

**Comment by petebacondarwin** [comment]
@GregBrimble - I tried changing that line but still got the error.

From what I can make out it is miniflare that is dispatching the response, but I guess that is just being proxied from svelte?

**Comment by petebacondarwin** [comment]
We've found the issue. The problem is in the Miniflare proxy. @GregBrimble is working on a fix. In the meantime, you can (sort of) workaround this by building the Svelte app and then running the build output via pages directly...

```bash
npm run build
npx wrangler pages dev .svelte-kit/cloudflare
```

**Comment by petebacondarwin** [comment]
Fix here: https://github.com/cloudflare/miniflare/pull/172
