### ISSUE TITLE
TypeError: localWebsocket.destroy is not a function

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#463]
This happened promptly after `ctrl-s` when using `wrangler dev`:

```
⎔ Detected changes, restarted server.
Something went wrong:
TypeError: localWebsocket.destroy is not a function
    at /Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:135227:24
    at /Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:135234:45
    at Array.forEach (<anonymous>)
    at /Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:135234:24
    at Object.invokeGuardedCallbackProd (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:43169:19)
    at invokeGuardedCallback (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:43256:39)
    at flushPassiveEffectsImpl (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:45813:19)
    at unstable_runWithPriority (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:29733:20)
    at runWithPriority (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:36513:18)
    at flushPassiveEffects (/Users/ashcon/.npm/_npx/c2aa6e5773d6d3ef/node_modules/wrangler/wrangler-dist/cli.js:45740:22)
```

**Comment by petebacondarwin** [comment]
Indeed the `faye-websocket` library that we are using does not have a `destroy()` method: https://github.com/faye/faye-websocket-node#websocket-api

**Comment by threepointone** [comment]
Hrmm I should've tested the websocket flow throughly, sorry about that. I assume we can replace it with .close and that should fix this specific issue.

**Comment by Electroid** [comment]
Still an issue. I can reproduce when the WebSocket is left for a few minutes (5-10)

**Comment by JacobMGEvans** [comment]
@rita3ko

**Comment by petebacondarwin** [comment]
I believe this is no longer an issue. Closing for now, until we have a reproduction on the latest wrangler.
