### ISSUE TITLE
🐛 BUG: 'wrangler@2 pages publish' returns 504 or 503 failure

### ISSUE THREAD

**Issue by icedac** [cloudflare/wrangler2#960]
### What version of `Wrangler` are you using?

2

### What operating system are you using?

ubuntu-latest

### Describe the Bug

# RUNS

## GITHUB-ACTION: cloudflare/pages-action@v1.0.0
```
Run cloudflare/pages-action@v1.0.0
  with:
    apiToken: ***
    accountId: ***
    projectName: xxx-yyy-gitaction
    directory: ./public
    gitHubToken: ***
npm WARN exec The following package was not found and will be installed: wrangler@[2](...)
```

## wrangler COMMAND inside of cloudflare/pages-action@v1.0.0
```
Executing: npx wrangler@2 pages publish "./public" --project-name="xxx-yyy-gitaction" in /home/runner/work/xxx-yyy/xxx-yyy
```

### 504
```
🌎  Uploading... (701/708)

✘ [ERROR] ✘ [ERROR] Received a malformed response from the API


🌎  Uploading... (701/708)
  

    <!DOCTYPE html>
    <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
    <!--[if I... (length = 7018)
  
    POST /accounts/***/pages/projects/xxx-yyy-gitaction/file -> 504 Gateway Time-out
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new
  
  


npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.9.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.9.0>
npm notice Run `npm install -g npm@8.9.0` to update!
npm notice 
EXIT WHEN NOT EXPECTED

SHELLAC COMMAND FAILED!
Executing: npx wrangler@2 pages publish "./public" --project-name="xxx-yyy-gitaction" in /home/runner/work/xxx-yyy/xxx-yyy
```

### fetch ERROR
```

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
🌏  Uploading... (706/709)



STDERR:

npm WARN exec The following package was not found and will be installed: wrangler@2
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
✘ [ERROR] fetch failed


npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.9.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.9.0>
npm notice Run `npm install -g npm@8.9.0` to update!
npm notice 
```

### another error
```
🌏  Uploading... (696/708)


🌏  Uploading... (696/708)



STDERR:

npm WARN exec The following package was not found and will be installed: wrangler@2
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
✘ [ERROR] ✘ [ERROR] Received a bad response from the API

  
    An unknown error occurred [code: 8000000]
    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new
```

## Descriptions:
- wrangler returns 503, 504, or just "[ERROR] fetch failed"
- I tried manual upload deployments
  - sometimes success, upload failed tens of files

**Comment by threepointone** [comment]
I believe we were having a minor outage at the time that got resolved quickly. Closing this, but lemme know if you gave any more issues.

**Comment by kjk** [comment]
Have the same problem. Failed 3 times in a row:
```
npx wrangler pages publish --project-name sumcrashes .

✘ [ERROR] ✘ [ERROR] Received a malformed response from the API


    <html>
    <head><title>502 Bad Gateway</title></head>
    <body>
    <center><h1>502 Bad Gateway</h1></cente... (length = 155)

    POST /accounts/71694ef61795ecbe1bc331d217dbd7a7/pages/projects/sumcrashes/file -> 502 Bad
  Gateway

    If you think this is a bug, please open an issue at:
    https://github.com/cloudflare/wrangler2/issues/new

🌍  Uploading... (27/84)
```

I was able to upload via web interface

**Comment by threepointone** [comment]
@GregBrimble

**Comment by ryo33** [comment]
Same here, it sometimes succeeds.

**Comment by GregBrimble** [comment]
Hey folks! Sorry about the difficulties here. We had hoped to move onto a system that let you publish files outside of using our API directly, but we didn't quite get there in time for the launch. This is pretty much the first thing on our list as fast-follow from this announcement, so please bear with us for a little while as we move things over.

**Comment by Disturbing** [comment]
> Hey folks! Sorry about the difficulties here. We had hoped to move onto a system that let you publish files outside of using our API directly, but we didn't quite get there in time for the launch. This is pretty much the first thing on our list as fast-follow from this announcement, so please bear with us for a little while as we move things over.

Any timeframe on the fast follow up? No pressure, just want to understand.

**Comment by bardouni** [comment]
@martinfojtik 
can u please check this: https://github.com/cloudflare/wrangler2/issues/1015 and confirm if this is same as your case.

**Comment by bodazhao** [comment]
Also had the issue of `✘ [ERROR] fetch failed` when trying to `wrangler kv:key put` on wrangler 2.0.5, after some debugging, found that downgrading `node` from v18 to v16 worked for me. 

p.s although the `kv put` operation worked, I did not see the `✨ Success` message like the doc suggested

**Comment by petebacondarwin** [comment]
@bodazhao - your comment does not seem related to this issue, unless I am misunderstanding? Please could you create a new issue with this problem?

**Comment by brycewray** [comment]
Possibly connected to https://github.com/cloudflare/pages-action/issues/8? Similar error message re `malformed response from the API`.

**Comment by icedac** [comment]
today I got another error.

```
🌍  Uploading... (801/801)

✨ Success! Uploaded 801 files (10.57 sec)

Using cached values in 'node_modules/.cache/wrangler'. This is used as a temporary store to improve the developer experience for some commands. It may be purged at any time. It doesn't contain any sensitive information, but it should not be commited into source control.

✘ [ERROR] Cannot read properties of null (reading 'url')


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.11.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.11.0>
npm notice Run `npm install -g npm@8.11.0` to update!
npm notice 
EXIT WHEN NOT EXPECTED

SHELLAC COMMAND FAILED!
Executing: npx wrangler@2 pages publish "./public" --project-name=xxx-yyy-gitaction" in /home/runner/work/xxx-yyy/xxx-yyy

node:internal/process/promises:246
STDOUT:
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

```

**Comment by GregBrimble** [comment]
Hey folks! We released 2.0.7 a little while ago which takes a new approach to uploading files for `wrangler pages publish`. It also adds retry logic, so hopefully things are a lot more reliable for you. I'll close this issue out, but if you continue to have problems, please do open a new issue.

**Comment by loozhengyuan** [comment]
I have been using using `2.0.7` for the past week or so, but i'm still encountering intermittent failures. Sometimes it succeeds, sometimes it doesn't.

**Comment by hvojdani** [comment]
I have this problem again:

wrangler pages deploy ./frontend/dist/frontend/ --project-name=front-demo --branch=main
Received a malformed response from the API
  upstream connect error or disconnect/reset before headers. reset reason: connection termination
  GET /accounts/*****/pages/projects/front-demo -> 503 Service Unavailable
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
