### ISSUE TITLE
🐛 BUG: with a custom route defined, `wrangler dev` tries to request data from the wrong host when starting up

### ISSUE THREAD

**Issue by miunau** [cloudflare/wrangler2#976]
### What version of `Wrangler` are you using?

2.0.3

### What operating system are you using?

Mac

### Describe the Bug

1. I have a route defined like so:
```
routes = [{ pattern = "*foo.bar.com/*", zone_name = "bar.com" }]
```

2. I start up `wrangler dev`
3. Wrangler tries to request `bar.com/cdn-cgi/workers/preview`, not `foo.bar.com`
4. Wrangler dies with `✘ [ERROR] Error on remote worker: SyntaxError: Unexpected token < in JSON at position 0` as it blindly tries to parse the incoming HTML from the wrong host as JSON.

Notes:
- `wrangler dev` works if I remove the route
- `wrangler dev --local` works
- `foo.bar.com` is routed to `192.0.2.1` in the DNS settings, and proxied through CF
- `bar.com` is routed to another public IP, and not proxied

**Comment by threepointone** [comment]
good catch! we should fix this

**Comment by miunau** [comment]
Thanks, currently blocking me from testing the R2 stuff without publishing

**Comment by miunau** [comment]
> A workaround for now is to add this to your `wrangler.toml`:
> 
> ```toml
> [dev]
> host = "foo.bar.com"
> ```

Just got to try this, doesn't seem like it works- I still get the same error.

**Comment by threepointone** [comment]
That's weird, sorry about that. I'll have a look at this early tomorrow.

**Comment by threepointone** [comment]
@miunau Could you clarify some things for me? 
- Is your zone_name is a substring of the pattern, like you described?
- What was the value you used for `[dev.host]`? Specifically, dod you add a leading `*.` to it?
- Do foo.bar.com and bar.com have different zone ids? Or are they under the same zone?

**Comment by threepointone** [comment]
Could you try with `wrangler@beta` and see if the bug persists?

**Comment by miunau** [comment]
> @miunau Could you clarify some things for me?
> 
> * Is your zone_name a substring of the pattern, like you described?

The zone name is the root of the domain (`bar.com`)

> * What was the value you used for `[dev.host]`? Specifically, dod you add a leading `*.` to it?

No, it was in the form of `host = "foo.bar.com"`.

> * Do foo.bar.com and bar.com have different zone ids? Or are they under the same zone?

They're under the same zone.

**Comment by tklae** [comment]
> Could you try with `wrangler@beta` and see if the bug persists?

Not the OP but experiencing the same problem, just tried it with `wrangler@beta` and it works there.

**Comment by threepointone** [comment]
I suspect this PR https://github.com/cloudflare/wrangler2/pull/1213 might have fixed this issue. Could you check, @miunau?
